### ISSUE TITLE
"Failed to Load" after update

### ISSUE THREAD

**Issue by hatchitdesign** [phdesign/NppToolBucket#14]
Hi,

Fantastic Plugin, so I'm very upset it's stopped working!

This problem has occurred since updating Notepad++ to the latest version (6.7.9.2).

Everytime I load Notepad I get a "Failed to load" message which states the plugin isn't compatible with this version of Notepad.

I've tried installing earlier copies of Notepad such as 5, 6.5 and a few others but nothing works.

Stumped!

**Comment by phdesign** [comment]
Hi,

Thanks for getting in touch. This is a problem that a few users have raised
but I've been unable to replicate and solve, do you mind answering a few
questions for me to help diagnose the problem?


   - How did you download and install Notepad++? E.g. from the website
   using the installer or zip package
   - What version of windows are using? E.g. Control Panel > System. Does
   System type 64-bit or 32-bit?
   - Can you right click on <<Notepad++ Folder>>\plugins\NppToolBucket.dll
   and click on Properties, does it say anything about Unblock?

Kind regards,

Paul

**Comment by hatchitdesign** [comment]
Hi Paul,

Thanks for your email. In answer to your questions:

- How did you download and install Notepad++? E.g. from the website using
the installer or zip package. *Yes from the Notepad++ website, downloaded a
ZIP and used the installation wizard.*
- What version of windows are using? E.g. Control Panel > System. Does
System type 64-bit or 32-bit? *Yes Windows 8.1, 64-bit*
- Can you right click on <<Notepad++ Folder>>\plugins\NppToolBucket.dll and
click on Properties, does it say anything about Unblock? *No nothing about
blocking, I've also tried to change the permissions to full rights for all
applications but this doesn't work either.*

On Tue, Jul 28, 2015 at 11:23 AM, Paul Heasley <notifications@github.com>
wrote:

> Hi,
>
> Thanks for getting in touch. This is a problem that a few users have raised
> but I've been unable to replicate and solve, do you mind answering a few
> questions for me to help diagnose the problem?
>
>
> - How did you download and install Notepad++? E.g. from the website
> using the installer or zip package
> - What version of windows are using? E.g. Control Panel > System. Does
> System type 64-bit or 32-bit?
> - Can you right click on <<Notepad++ Folder>>\plugins\NppToolBucket.dll
> and click on Properties, does it say anything about Unblock?
>
> Kind regards,
>
> Paul
>
> On 20 July 2015 at 01:14, hatchitdesign <notifications@github.com> wrote:
>
> > Hi,
> >
> > Fantastic Plugin, so I'm very upset it's stopped working!
> >
> > This problem has occurred since updating Notepad++ to the latest version
> > (6.7.9.2).
> >
> > Everytime I load Notepad I get a "Failed to load" message which states
> the
> > plugin isn't compatible with this version of Notepad.
> >
> > I've tried installing earlier copies of Notepad such as 5, 6.5 and a few
> > others but nothing works.
> >
> > Stumped!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/phdesign/NppToolBucket/issues/14>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phdesign/NppToolBucket/issues/14#issuecomment-125544324>
> .
>



-- 
Regards,

Ben Gidney

*Web Designer* |
*0208 466 8160*
hatchitdesign.com

**Comment by phdesign** [comment]
Thanks for this, I'll try replicating again and see if I can isolate the
problem.

Thanks,

Paul
