### ISSUE TITLE
Output path non-standard

### ISSUE THREAD

**Issue by moon6969** [phdesign/NppToolBucket#20]
Hi Paul,

Thanks for new version 1.9... just noticed though that the output path in the project file is hard-coded to _your_ user profile folder.

At the very least it could go to _my_ user profile if not the more standard "bin/debug" :-)

**Comment by phdesign** [comment]
Thanks for the reminder! I remember putting that in and thinking //TODO: Remove my hardcoded path, but of course promptly forgot. Will fix.

**Comment by phdesign** [comment]
Fixed by 4a1e2a8
