### ISSUE TITLE
search and replace in directories

### ISSUE THREAD

**Issue by pouemes** [phdesign/NppToolBucket#25]
is there a solution to use toolbucket with files in subdirectories?
thanks

**Comment by phdesign** [comment]
Hi! Unfortunately no. I don't plan to support searching the file system (I feel there are a lot of great other tools that do this).

**Comment by colvdv** [comment]
> Hi! Unfortunately no. I don't plan to support searching the file system (I feel there are a lot of great other tools that do this).

I grabbed NppToolBucket hoping I'd be able to do a multi-line Find & Replace throughout my entire directory and all subdirectories, basically like the Find & Replace in Files feature already built-in to Notepad++, but multi-line. This feature would be greatly appreciated!
