### ISSUE TITLE
64 bit notepad++

### ISSUE THREAD

**Issue by noxtras** [phdesign/NppToolBucket#6]
Hello,
I don't know why, I can't seem to be able to start your plugin. I'm using Win8 64bit with 64 bit Notepad++.  I can see the plugin with the plugin manager, but other then that I don't know how to launch it.
Thank you.

**Comment by phdesign** [comment]
Thanks to @chcg I've built a 64-bit version, available here: http://phdesign.com.au/npptoolbucket/

**Comment by chcg** [comment]
See also x64 of PluginManager at https://github.com/bruderstein/nppPluginManager/releases/tag/v1.4.9
